name: memcached
description: A simple Memcached cluster
version: 0.1.0
home: http://https://hub.docker.com/_/memcached/
maintainers:
- name: Matt Butcher
  email: mbutcher@deis.com
details: |-
  Memcached is a simple cache server. This chart provides multiple replication
  controllers that can be grouped together into a cluster.
